export const GET_QUESTIONS_REQUEST = "GET_QUESTIONS_REQUEST";
export const GET_QUESTIONS_FAILED = "GET_QUESTIONS_FAILED";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";

export const SAVE_QUESTION_REQUEST = "SAVE_QUESTION_REQUEST";
export const SAVE_QUESTION_FAILED = "SAVE_QUESTION_FAILED";
export const SAVE_QUESTION_SUCCESS = "SAVE_QUESTION_SUCCESS";
export const SAVE_USER_QUESTION_SUCCESS = "SAVE_USER_QUESTION_SUCCESS";

export const SAVE_ANSWER_REQUEST = "SAVE_ANSWER_REQUEST";
export const SAVE_ANSWER_FAILED = "SAVE_ANSWER_FAILED";
export const SAVE_ANSWER_SUCCESS = "SAVE_ANSWER_SUCCESS";
