export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_FAILED = "GET_USERS_FAILED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_FAILED = "ADD_USER_FAILED";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
